### PR TITLE
Adjust common arch flags

### PR DESCRIPTION
**Pull request by chuckatkins**
This primarily moves common architecture flags from the `CMAKE_CXX_FLAGS` variable to target properties instead.  The intent is to prevent clashing with multiple arch flags in the kernel compilation.  The current behavior is for the kernels to be compiled with `FLAGS_SSE2` AND `FLAGS_<ARCH>` which leads to noisy warnings on some compilers, specifically with the CrayPE wrappers, but also with Intel compilers when multiple `-xARCH` flags are used on the same command line.

### CODE REVIEW

**Comment by svenwoop** [comment]
This fix will be released in Embre 3.1

**Comment by chuckatkins** [comment]
@svenwoop Is this pr closed and the issue will be fixed differently or is it merged somewhere?  A side effect of this pr fixes a build failure on Cray so I'm just trying to figure out if I need to make a separate PR with just that fix or if this will end up getting pulled in somewhere.

**Comment by svenwoop** [comment]
I pulled in these 3 commits to our internal devel branch (not visible at GitHub). Just had to do some fixes to your fix (gcc.cmake -> gnu.cmake, incude(icc) -> include(intel) for windows, and add FLAGS_LOWEST to remaining targets). We will release this fix with Embree 3.1.

**Comment by chuckatkins** [comment]
I just caught that too with some extra testing.  Thanks.

**Pull request closed without merging**
