### PR TITLE
add an alternate search path for find tbb on windows

### PR DESCRIPTION
**Pull request by demarle**
In paraview superbuild, we tend to get tbb from a scratch
directory. This change makes sure embree can search in that
location as well as system install places where it already looks.

### CODE REVIEW

**Comment by demarle** [comment]
I'm not seeing this anywhere in the history. Did master get force pushed or something after Jul 17? ParaView will have to maintain it's patch unfortunately.

**Comment by svenwoop** [comment]
Sorry, this was merged into master branch (but should have gotten merged into devel). We let point master always to the latest release.

Does the above commit fixe the issue? I just added the EMBREE_TBB_ROOT/lib as additional search path.

BTW, you can also set EMBREE_TBB_ROOT to the empty string, and then set the location of the TBB library paths manually through TBB_LIBRARY=XXXXXXX, etc.

**Comment by demarle** [comment]
Build finds tbb with your version and compiles now, but we still get an install failure when the superbuild installs embree into its scratch space.
CMake Error at cmake_install.cmake:63 (file):
  file INSTALL cannot find
  "C:/Users/dave.demarle/Builds/PARAVIEW/PVSB13master/install/bin/intel64/vc12/tbb.dll".

**Comment by demarle** [comment]
And for what it's worth the ParaView project doesn't need or really want embree to install tbb. We'd rather tbb take care of installing tbb.

**Comment by mathstuf** [comment]
Yeah, Embree installing TBB should really be an option (and, IMO, default to not doing so).

**Comment by svenwoop** [comment]
Will add an option to enable Embree to install TBB under Windows and make this default off.

**Comment by johguenther** [comment]
In OSPRay we have an `OSPRAY_INSTALL_DEPENDENCIES` to control this for all platforms and for all dependencies (like embree ;-).

**Comment by svenwoop** [comment]
Embree 2.17.1 will have an EMBREE_INSTALL_DEPENDENCIES option (default OFF) to fix this issue.

**Pull request merged**
