### PR TITLE
Fixed #359: Support compiling to WebAssembly using Emscripten

### LINKED ISSUE #359: Support compiling to WebAssembly using Emscripten
When compiling to WebAssembly (WASM) using [Emscripten](https://emscripten.org/), several problems appear. Some are CMake configuration issues, others are limitations in WASM's support for [threads](https://emscripten.org/docs/porting/pthreads.html) or [SIMD intrinsics](https://emscripten.org/docs/porting/simd.html), and still others relate to assumptions Embree code makes about sizes of basic types like `size_t` that don't hold in WASM.

I will open a PR with proposed changes.

### PR DESCRIPTION
**Pull request by estollnitz**
## Changes

CMake configuration changes when compiling with Emscripten:
- Disable support for Intel's ISPC (Implicit SPMD Program Compiler).
- Default to SSE2 instruction set architecture — higher ISAs do not work yet in WASM.
- Add compiler flags to enable exceptions, pthreads, and SIMD instructions.
- Add link flags to `tutorials/embree_tests` that permit running these tests with Node.js.

Code changes when compiling with Emscripten:
- Provide `min()`, `max()` overloads that take `size_t` and `long`.
- Provide `StackArray::operator[]` and `DynamicStackArray::operator[]` overloads that take `size_t`.
- Provide `bsr()` overload that takes `unsigned`.
- Avoid ambiguous cast error by leaving out cast operators that are no-ops in common/simd/vboolf4_sse2.h.
- Provide stubs for `_MM_SET_EXCEPTION_MASK` and `_mm_setcsr` in common/simd/wasm/emulation.h (these are unavailable in WASM according to the [docs](https://emscripten.org/docs/porting/simd.html#compiling-simd-code-targeting-x86-sse-instruction-set)).
- Claim support for SSE2 instructions in `getCPUFeatures()`.
- Implement `getNumberOfLogicalThreads()` by querying the browser or Node.js for the number of logical threads using JavaScript.
- Avoid overflow in `parallel_partition` test by using `uint64_t` (`size_t` has only 32 bits in WASM).

## Build instructions

To build, you will need the latest [Emscripten SDK](https://emscripten.org/docs/getting_started/downloads.html).

```sh
mkdir build
cd build
emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DEMBREE_TUTORIALS=OFF
emmake make -j
```

### CODE REVIEW

**Comment by svenwoop** [comment]
I did merge this into our internal devel branch and also enabled some CI testing to build using WebAssembly. This will be in the next release.

As tasking system I had to use INTERNAL, is that expected?

**Comment by estollnitz** [comment]
> I did merge this into our internal devel branch and also enabled some CI testing to build using WebAssembly. This will be in the next release.

Thanks, @svenwoop.
 
> As tasking system I had to use INTERNAL, is that expected?

Yes, I should have mentioned that the `INTERNAL` tasking system is the only one that works straightaway with WebAssembly. I have also been able to get `EMBREE_TASKING_SYSTEM=TBB` working, but only because I'm using a version of oneTBB that has been modified somewhat to build with Emscripten. I hope to get those changes into oneTBB as well.

Just so you know, aside from some application tests of my own, I only tested with `tutorials/embree_tests`. It would be nice if there were a CMake configuration option that enabled just these simple tests, since they have no other dependencies.

**Comment by marklundin** [comment]
Just to clarify, did this PR get merged?

**Comment by svenwoop** [comment]
Yes latest Embree release compiles to WebAssembly using Emscripten.

**Comment by manuel5975p** [comment]
It doesn't seem to work anymore: Embree's CMakeLists appends the flag `-mno-sse4.2` which emscripten does not recognize.

**Comment by Innovgame** [comment]
I have the same problem.
You can solve it this way. @manuel5975p 
https://github.com/RenderKit/embree/issues/486 https://github.com/RenderKit/embree/commit/cda4cf1919bb2a748e78915fbd6e421a1056638d

**Pull request closed without merging**
